from tkinter import *
import tkinter as tk
import os
from tkinter import messagebox
prog_call = sys.argv[0]
prog_location = os.path.split(prog_call)[0]
class cwin:
    def custwindow(self):
        #----------------------------------------
        import datetime
        today=datetime.date.today()

        f=open("data.txt",'r')
        logindata=f.read()
        #x=int(logindata)
        print(logindata)
        #-------------------------------------
        import sqlite3
        con = sqlite3.connect("mess.db")
        cursor = con.execute("select * from user_data where Id = "+logindata)
        for row in cursor:
            idi=row[0]
            self.name=row[1]
            sdate=row[5]
        print("the data is")
        print(idi,self.name,sdate)

        #------------------------------------------------------------------------
        d1=open("dish1.txt",'r')
        self.dish11=d1.read()
        d1.close()
        d2=open("dish2.txt",'r')
        self.dish22=d2.read()
        d2.close()
        #------------------------------------------------------------------------
        self.top = Toplevel()
        self.top.geometry("910x633+571+230")
        self.top.title("New Toplevel")
        self.top.configure(background="#34c8d8")

        self.cf1 = tk.Frame(self.top)
        self.cf1.place(relx=0.0, rely=0.0, relheight=0.292, relwidth=1.005)
        self.cf1.configure(relief='groove')
        self.cf1.configure(borderwidth="2")
        self.cf1.configure(relief="groove")
        self.cf1.configure(background="#1b8cb5")
        self.cf1.configure(width=915)

        self.lbl1 = tk.Label(self.cf1)
        self.lbl1.place(relx=0.197, rely=0.216, height=41, width=227)
        self.lbl1.configure(background="#1b8cb5")
        self.lbl1.configure(disabledforeground="#a3a3a3")
        self.lbl1.configure(font="-family {Segoe UI Black} -size 15 -weight bold")
        self.lbl1.configure(foreground="#fef5ff")
        self.lbl1.configure(text='''Welcome''')
        self.lbl1.configure(width=227)

        self.username = tk.Label(self.cf1)
        self.username.place(relx=0.219, rely=0.432, height=41, width=150)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#1b8cb5")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="-family {Segoe UI Emoji} -size 14 -weight bold")
        self.username.configure(foreground="#fef5ff")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text=self.name)
        self.username.configure(width=107)

        self.lblid = tk.Label(self.cf1)
        self.lblid.place(relx=0.24, rely=0.649, height=41, width=107)
        self.lblid.configure(activebackground="#f9f9f9")
        self.lblid.configure(activeforeground="black")
        self.lblid.configure(background="#1b8cb5")
        self.lblid.configure(disabledforeground="#a3a3a3")
        self.lblid.configure(font="-family {Segoe UI Emoji} -size 14 -weight bold")
        self.lblid.configure(foreground="#fef5ff")
        self.lblid.configure(highlightbackground="#d9d9d9")
        self.lblid.configure(highlightcolor="black")
        self.lblid.configure(text='''Id No:''')

        self.Button2 = tk.Button(self.cf1,command=self.lgou)
        self.Button2.place(relx=0.842, rely=0.324, height=52, width=108)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Tahoma} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''LOGOUT''')
        self.Button2.configure(width=108)

        self.lblic = tk.Label(self.cf1)
        self.lblic.place(relx=0.022, rely=0.054, height=152, width=151)
        self.lblic.configure(background="#1b8cb5")
        self.lblic.configure(cursor="fleur")
        self.lblic.configure(disabledforeground="#a3a3a3")
        self.lblic.configure(foreground="#000000")
        photo_location = os.path.join(prog_location, "MAN.png")
        self._img0 = tk.PhotoImage(file=photo_location)
        self.lblic.configure(image=self._img0)
        self.lblic.configure(text='''Label''')
        self.lblic.configure(width=151)

        self.lblda = tk.Label(self.cf1)
        self.lblda.place(relx=0.743, rely=0.703, height=41, width=67)
        self.lblda.configure(activebackground="#f9f9f9")
        self.lblda.configure(activeforeground="black")
        self.lblda.configure(background="#1b8cb5")
        self.lblda.configure(disabledforeground="#a3a3a3")
        self.lblda.configure(font="-family {Segoe UI Emoji} -size 9 -weight bold")
        self.lblda.configure(foreground="#fef5ff")
        self.lblda.configure(highlightbackground="#d9d9d9")
        self.lblda.configure(highlightcolor="black")
        self.lblda.configure(text='''Date :''')
        self.lblda.configure(width=67)

        self.datedisplay = tk.Label(self.cf1)
        self.datedisplay.place(relx=0.809, rely=0.703, height=41, width=107)
        self.datedisplay.configure(activebackground="#f9f9f9")
        self.datedisplay.configure(activeforeground="black")
        self.datedisplay.configure(background="#1b8cb5")
        self.datedisplay.configure(disabledforeground="#a3a3a3")
        self.datedisplay.configure(font="-family {Segoe UI Emoji} -size 9 -weight bold")
        self.datedisplay.configure(foreground="#fef5ff")
        self.datedisplay.configure(highlightbackground="#d9d9d9")
        self.datedisplay.configure(highlightcolor="black")
        self.datedisplay.configure(text=today)
        self.datedisplay.configure(width=107)

        self.idname = tk.Label(self.cf1)
        self.idname.place(relx=0.35, rely=0.649, height=41, width=107)
        self.idname.configure(activebackground="#f9f9f9")
        self.idname.configure(activeforeground="black")
        self.idname.configure(background="#1b8cb5")
        self.idname.configure(disabledforeground="#a3a3a3")
        self.idname.configure(font="-family {Segoe UI Emoji} -size 14 -weight bold")
        self.idname.configure(foreground="#fef5ff")
        self.idname.configure(highlightbackground="#d9d9d9")
        self.idname.configure(highlightcolor="black")
        self.idname.configure(text=idi)

        self.cf2 = tk.Frame(self.top)
        self.cf2.place(relx=0.0, rely=0.269, relheight=0.118, relwidth=1.005)
        self.cf2.configure(relief='groove')
        self.cf2.configure(borderwidth="2")
        self.cf2.configure(relief="groove")
        self.cf2.configure(background="#2733d8")
        self.cf2.configure(width=915)

        self.lbluse = tk.Label(self.cf2)
        self.lbluse.place(relx=0.262, rely=0.267, height=41, width=457)
        self.lbluse.configure(activebackground="#f9f9f9")
        self.lbluse.configure(activeforeground="black")
        self.lbluse.configure(background="#2733d8")
        self.lbluse.configure(disabledforeground="#a3a3a3")
        self.lbluse.configure(font="-family {Segoe UI Black} -size 15 -weight bold")
        self.lbluse.configure(foreground="#fef5ff")
        self.lbluse.configure(highlightbackground="#d9d9d9")
        self.lbluse.configure(highlightcolor="black")
        self.lbluse.configure(text='''USER SECTION''')
        self.lbluse.configure(width=457)

        self.dishname1 = tk.Button(self.top,command=self.dish1)
        self.dishname1.place(relx=0.187, rely=0.506, height=82, width=228)
        self.dishname1.configure(activebackground="#ececec")
        self.dishname1.configure(activeforeground="#000000")
        self.dishname1.configure(background="#d9d9d9")
        self.dishname1.configure(disabledforeground="#a3a3a3")
        self.dishname1.configure(font="-family {Segoe UI} -size 14")
        self.dishname1.configure(foreground="#000000")
        self.dishname1.configure(highlightbackground="#d9d9d9")
        self.dishname1.configure(highlightcolor="black")
        self.dishname1.configure(pady="0")
        self.dishname1.configure(text=self.dish11)
        self.dishname1.configure(width=228)

        self.dishname2 = tk.Button(self.top,command=self.dish2)
        self.dishname2.place(relx=0.56, rely=0.506, height=82, width=228)
        self.dishname2.configure(activebackground="#ececec")
        self.dishname2.configure(activeforeground="#000000")
        self.dishname2.configure(background="#d9d9d9")
        self.dishname2.configure(disabledforeground="#a3a3a3")
        self.dishname2.configure(font="-family {Segoe UI} -size 14")
        self.dishname2.configure(foreground="#000000")
        self.dishname2.configure(highlightbackground="#d9d9d9")
        self.dishname2.configure(highlightcolor="black")
        self.dishname2.configure(pady="0")
        self.dishname2.configure(text=self.dish22)

        self.cf3 = tk.Frame(self.top)
        self.cf3.place(relx=0.0, rely=0.9, relheight=0.087, relwidth=0.995)
        self.cf3.configure(relief='groove')
        self.cf3.configure(borderwidth="2")
        self.cf3.configure(relief="groove")
        self.cf3.configure(background="#2733d8")
        self.cf3.configure(width=905)

        self.lblstrat = tk.Label(self.cf3)
        self.lblstrat.place(relx=-0.022, rely=0.182, height=41, width=227)
        self.lblstrat.configure(activebackground="#f9f9f9")
        self.lblstrat.configure(activeforeground="black")
        self.lblstrat.configure(background="#2733d8")
        self.lblstrat.configure(disabledforeground="#a3a3a3")
        self.lblstrat.configure(font="-family {Segoe UI Semibold} -size 10 -weight bold")
        self.lblstrat.configure(foreground="#ffffff")
        self.lblstrat.configure(highlightbackground="#d9d9d9")
        self.lblstrat.configure(highlightcolor="black")
        self.lblstrat.configure(text='''Tifin Start date :''')

        self.sdate = tk.Label(self.cf3)
        self.sdate.place(relx=0.188, rely=0.182, height=41, width=157)
        self.sdate.configure(activebackground="#f9f9f9")
        self.sdate.configure(activeforeground="black")
        self.sdate.configure(background="#2733d8")
        self.sdate.configure(disabledforeground="#a3a3a3")
        self.sdate.configure(font="-family {Segoe UI Semibold} -size 10 -weight bold")
        self.sdate.configure(foreground="#ffffff")
        self.sdate.configure(highlightbackground="#d9d9d9")
        self.sdate.configure(highlightcolor="black")
        self.sdate.configure(text=sdate)
        self.sdate.configure(width=157)

        self.lblrem = tk.Label(self.cf3)
        self.lblrem.place(relx=0.453, rely=0.182, height=41, width=157)
        self.lblrem.configure(activebackground="#f9f9f9")
        self.lblrem.configure(activeforeground="black")
        self.lblrem.configure(background="#2733d8")
        self.lblrem.configure(disabledforeground="#a3a3a3")
        self.lblrem.configure(font="-family {Segoe UI Semibold} -size 10 -weight bold")
        self.lblrem.configure(foreground="#ffffff")
        self.lblrem.configure(highlightbackground="#d9d9d9")
        self.lblrem.configure(highlightcolor="black")
        self.lblrem.configure(text='''Days Remaining :''')

        self.remaining = tk.Label(self.cf3)
        self.remaining.place(relx=0.641, rely=0.182, height=41, width=157)
        self.remaining.configure(activebackground="#f9f9f9")
        self.remaining.configure(activeforeground="black")
        self.remaining.configure(background="#2733d8")
        self.remaining.configure(disabledforeground="#a3a3a3")
        self.remaining.configure(font="-family {Segoe UI Semibold} -size 10 -weight bold")
        self.remaining.configure(foreground="#ffffff")
        self.remaining.configure(highlightbackground="#d9d9d9")
        self.remaining.configure(highlightcolor="black")
        self.remaining.configure(text='''data''')

        self.lblspe = tk.Label(self.top)
        self.lblspe.place(relx=0.011, rely=0.395, height=41, width=227)
        self.lblspe.configure(activebackground="#f9f9f9")
        self.lblspe.configure(activeforeground="black")
        self.lblspe.configure(background="#34c8d8")
        self.lblspe.configure(disabledforeground="#a3a3a3")
        self.lblspe.configure(font="-family {Segoe UI Semibold} -size 14 -weight bold")
        self.lblspe.configure(foreground="#ffffff")
        self.lblspe.configure(highlightbackground="#d9d9d9")
        self.lblspe.configure(highlightcolor="black")
        self.lblspe.configure(text='''Today's Special''')

        self.skipbutt = tk.Button(self.top,command=self.skipb)
        self.skipbutt.place(relx=0.824, rely=0.774, height=52, width=118)
        self.skipbutt.configure(activebackground="#ececec")
        self.skipbutt.configure(activeforeground="#000000")
        self.skipbutt.configure(background="#d9d9d9")
        self.skipbutt.configure(disabledforeground="#a3a3a3")
        self.skipbutt.configure(foreground="#000000")
        self.skipbutt.configure(highlightbackground="#d9d9d9")
        self.skipbutt.configure(highlightcolor="black")
        self.skipbutt.configure(pady="0")
        self.skipbutt.configure(text='''Skip tifin''')
        self.skipbutt.configure(width=118)
        self.top.mainloop()

        #----------------------------------
        #-------------------------------------
    def lgou(self):
        self.top.destroy()
    def dish2(self):
        self.dishname1.configure(state=DISABLED)
        self.dishname2.configure(state=DISABLED)
        self.skipbutt.configure(state=DISABLED)
        messagebox.showinfo("sucess","you select  "+self.dish11)
        f=open("response.txt",'a')
        f.write("\n")
        f.write(self.name+"      "+self.dish11)
        f.close()
    def dish1(self):
        self.dishname1.configure(state=DISABLED)
        self.dishname2.configure(state=DISABLED)
        self.skipbutt.configure(state=DISABLED)
        messagebox.showinfo("sucess","you select  "+ self.dish22)
        f = open("response.txt", 'a')
        f.write("\n")
        f.write(self.name + "      " + self.dish22)
        f.close()
    def skipb(self):
        self.dishname1.configure(state=DISABLED)
        self.dishname2.configure(state=DISABLED)
        self.skipbutt.configure(state=DISABLED)
        messagebox.showinfo("sucess", "you skip the tifin")
        f = open("response.txt", 'a')
        f.write("\n")
        f.write(self.name + "      skip tifin")
        f.close()
